## Numpy array (What is Numpy array)

In [3]:
#install numpy package
!pip3 install numpy

Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable


In [4]:
#import numpy as np
import numpy as np

## Creating Numpy array

In [7]:
import numpy as np

#tinggi badan
tinggi_badan = np.array([1.50, 1.60, 1.70, 1.65, 1.70, 1.68])
#berat badan
berat_badan = np.array([40, 50, 60, 70, 70, 50])

#menghitung BMI (Boddy Mass Index)
BMI = berat_badan / tinggi_badan ** 2
print(BMI)

[17.77777778 19.53125    20.76124567 25.71166208 24.22145329 17.7154195 ]


In [8]:
#numpy array limitations
np.array(["Saya", 100, True])

array(['Saya', '100', 'True'], dtype='<U21')

In [17]:
import numpy as np

#menjumlahkan dua array berikut
jajan_anak      = np.array([1000, 3000, 4000, 5000])
belanja_makanan = np.array([10000, 40000, 50000, 20000])

pengeluaran_harian = jajan_anak + belanja_makanan
print(pengeluaran_harian)

[11000 43000 54000 25000]


In [18]:
#hasilkan pegeluaran harian perbulan
pengeluaran_bulanan = pengeluaran_harian * 30
print(pengeluaran_bulanan)

[ 330000 1290000 1620000  750000]


In [21]:
#hasilkan pengeluaran per minggu
pengeluaran_mingguan = pengeluaran_bulanan / 4
print(pengeluaran_mingguan)

[ 82500. 322500. 405000. 187500.]


## Subsetting Numpy array

Subsetting NumPy array dengan [] Square Brackets

In [30]:
#tinggi badan pasien dalam (m)
tinggi_badan = np.array([1.70, 1.80, 1.65, 1.58, 1.89])
#pilih element index pertama dan ketiga
tinggi_badan[1:3]

array([1.8 , 1.65])

Subsetting dengan comparison operatos Hasilnya Boolean(Logic)

In [33]:
#berat badan pasien dalam (kg)
berat_badan = np.array([50, 70, 88, 90, 65])
pasien_obesitas = berat_badan > 75
print(pasien_obesitas)

[False False  True  True False]


## Numpy Multidimensional Array

Perbedaan dan persamaan dasar antara 1D NumPy array dan 2D NumPy array.


In [34]:
#1(Satu) Dimensional Array
    ##Tidak Memiliki Kolom
    ##Salah satu cara membuat 1D NumPy array yaitu dengan 1 list
    ##Hanya bisa terdiri dari 1 tipe data
    
#2(Dua) Dimensional Array
    ##Bisa memiliki Kolom
    ##Salah satu cara membuat 2D NumPy array yaitu dengan list of list
    ##Hanya bisa terdiri dari 1 tipe data

In [39]:
#membuat 2D array tim_basket dengan a List of List
tim_basket = [[180, 68.4],
              [190, 75],
              [183, 65.1],
              [186, 77.3],
              [198, 85.2]]

#create a 2D NumPy array from tim_basket: np_tim_basket
np_tim_basket = np.array(tim_basket)
#print out the shape of np_tim_basket
np_tim_basket.shape

#5 -> adalah jumlah baris(Row)
#2 -> adalah jumlah kolom(Column)

(5, 2)

## Calculating Numpy Array (Kalkulasi Numpy array)

In [97]:
#2D NumPy array : tinggi bada(cm), berat badan(kg)
tim_basket = np.array([[300, 68.4],
                       [190, 75],
                       [113, 65.1],
                       [186, 77.3],
                       [198, 85.2]])

In [98]:
#rubah tinggi badan ke satuan meter(m)
tinggi_meter = tim_basket[:, 0] / 100
print(tinggi_meter)

[3.   1.9  1.13 1.86 1.98]


In [100]:
#rubah tinggi badan index ke 0 hingga index ke 3
tinggi_meter = tim_basket[0:3:, 0] / 100
print("Tinggi dalam Meter dari index ke 0 hingga ke 3 :", tinggi_meter)
#hitung rata rata tinggi pemain dari index ke 0 hingga ke 3
mean = np.mean(tinggi_meter)
print("Rata - Rata tinggi pemain dari index ke 0 hingga ke 3 :", mean)
#hitung median(nilai tengah) dari index ke 0 hingga ke 3
median = np.median(tinggi_meter)
print("Nilai tengah tinggi pemain dari index ke 0 hingga ke 3 :", median)
np.std(tinggi_meter)

Tinggi dalam Meter dari index ke 0 hingga ke 3 : [3.   1.9  1.13]
Rata - Rata tinggi pemain dari index ke 0 hingga ke 3 : 2.0100000000000002
Nilai tengah tinggi pemain dari index ke 0 hingga ke 3 : 1.9


0.7673764830033996